### ISSUE TITLE
NameError:  name 're_path' is not defined

### ISSUE THREAD

**Issue by Maulth** [ppfeufer/aa-forum#100]
### Bug Description
I just installed AA-forum on a brand new installation of AA. In my attempt to run migrations after making the urls.py edit to match what was on the installation documentation, I was met with the error/traceback of:

`Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/home/allianceserver/venv/auth/lib/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/home/allianceserver/venv/auth/lib/python3.8/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/allianceserver/venv/auth/lib/python3.8/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/allianceserver/venv/auth/lib/python3.8/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/home/allianceserver/venv/auth/lib/python3.8/site-packages/django/core/management/base.py", line 89, in wrapped
    res = handle_func(*args, **kwargs)
  File "/home/allianceserver/venv/auth/lib/python3.8/site-packages/django/core/management/commands/migrate.py", line 75, in handle
    self.check(databases=[database])
  File "/home/allianceserver/venv/auth/lib/python3.8/site-packages/django/core/management/base.py", line 419, in check
    all_issues = checks.run_checks(
  File "/home/allianceserver/venv/auth/lib/python3.8/site-packages/django/core/checks/registry.py", line 76, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/home/allianceserver/venv/auth/lib/python3.8/site-packages/django/core/checks/urls.py", line 40, in check_url_namespaces_unique
    all_namespaces = _load_all_namespaces(resolver)
  File "/home/allianceserver/venv/auth/lib/python3.8/site-packages/django/core/checks/urls.py", line 57, in _load_all_namespaces
    url_patterns = getattr(resolver, 'url_patterns', [])
  File "/home/allianceserver/venv/auth/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/allianceserver/venv/auth/lib/python3.8/site-packages/django/urls/resolvers.py", line 602, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/allianceserver/venv/auth/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/allianceserver/venv/auth/lib/python3.8/site-packages/django/urls/resolvers.py", line 595, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/allianceserver/myauth/myauth/urls.py", line 17, in <module>
    re_path(
NameError: name 're_path' is not defined
`

### Expected behavior

My assumption is that the upgrade to django 4 is what caused this due to a restructuring of naming schema, but I am just a dabbler when it comes to the actual development of AA apps.

### Please complete the following information:

- AA-Forum Version: Current (1.8.0)
- Alliance Auth Version: 2.11.2

### Additional context

I managed to fix this (I think) by adding an extra import on 1st line
`from django.conf.urls import include, url, re_path`

After that, migrations went smoothly as re_path was then defined.

I've included a full snippet of my urls.py so you can see it in case the installation documentation needs to be updated.

`

**Comment by Maulth** [comment]
I think I got the markup wrong on that last code snippet.


`from django.conf.urls import include, url, re_path
from allianceauth import urls

urlpatterns = [
    url(r'', include(urls)),
]

# URL configuration for cKeditor
from django.apps import apps

if apps.is_installed("ckeditor"):
    from django.contrib.auth.decorators import login_required
    from django.views.decorators.cache import never_cache
    from ckeditor_uploader import views as ckeditor_views

    urlpatterns = [
        re_path(
            r"^upload/", login_required(ckeditor_views.upload), name="ckeditor_upload"
        ),
        re_path(
            r"^browse/",
            never_cache(login_required(ckeditor_views.browse)),
            name="ckeditor_browse",
        ),
    ] + urlpatterns

handler500 = 'allianceauth.views.Generic500Redirect'
handler404 = 'allianceauth.views.Generic404Redirect'
handler403 = 'allianceauth.views.Generic403Redirect'
handler400 = 'allianceauth.views.Generic400Redirect'`

**Comment by Maulth** [comment]
```
from django.conf.urls import include, url, re_path
from allianceauth import urls

urlpatterns = [
    url(r'', include(urls)),
]

# URL configuration for cKeditor
from django.apps import apps

if apps.is_installed("ckeditor"):
    from django.contrib.auth.decorators import login_required
    from django.views.decorators.cache import never_cache
    from ckeditor_uploader import views as ckeditor_views

    urlpatterns = [
        re_path(
            r"^upload/", login_required(ckeditor_views.upload), name="ckeditor_upload"
        ),
        re_path(
            r"^browse/",
            never_cache(login_required(ckeditor_views.browse)),
            name="ckeditor_browse",
        ),
    ] + urlpatterns

handler500 = 'allianceauth.views.Generic500Redirect'
handler404 = 'allianceauth.views.Generic404Redirect'
handler403 = 'allianceauth.views.Generic403Redirect'
handler400 = 'allianceauth.views.Generic400Redirect'

```

**Comment by ppfeufer** [comment]
You got the wrong import ...

It's
```py
from django.urls import include, re_path
```
In your case, can pretty much just copy-paste the URL conf from the install instructions, since you don't have any other modifications as it seems.
